### ISSUE TITLE
Terminate Command 

### ISSUE THREAD

**Issue by nephilimboy** [docker-java/docker-java#1020]
Hi,
how can i terminate infinite loop command that run with "execCreateCmd" like **ping** or any others ? here is my code
```
ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(ubuntu_container.getId())
                .withAttachStdout(true)
                .withCmd("ping", "google.com")
                .withUser("root")
                .exec();

        dockerClient.execStartCmd(execCreateCmdResponse.getId())
                .exec(new ExecStartResultCallback(System.out, System.err));
```
it ping google.com infinitely, how can i terminate it(something like **ctrl-c**) .

**Comment by bhowell2** [comment]
The answer you're probably looking for is: `dockerClient.stopContainerCmd(id)` -- so use the `execCreateCmdResponse.getId()`

**Comment by nephilimboy** [comment]
so when ever user in my webapp press ctrl-c in virtual terminal, i have to stop the container and then run it again for next command,,,is this the right way? i dont think so

**Comment by bhowell2** [comment]
so technically `ctrl-c` sends `SIGINT` and not `SIGTERM`. docker docs say that `docker stop` sends `SIGTERM`. this should work for most cases. if you're writing your own program you're gonna need to handle the cases as you best see fit.

I guess i'm a bit confused on what you're doing though. You DO want the container to terminate when the user connects to it in your webapp and then sends `ctrl-c` or you do NOT want the container to terminate? 
If the former is the case, i'm assuming that every time a user clicks the container on your webapp that you're spinning up a NEW container for them, yes? **How you're attaching to this container for the user is the real question then.** If you're using something like `docker exec -it container_name /bin/bash` and then they're calling `ctrl-c` it will NOT kill the main process, because it's not attached to the main process, it's actually attached to the `bash` process. If you're trying to kill the main process then you've gotta attach to the main process.

Again, I really don't know how you're attaching to the container and exactly what you're trying to do, so it's hard for me to say.

**Comment by nephilimboy** [comment]
"You DO want the container to terminate when the user connects to it in your webapp and then sends ctrl-c or you do NOT want the container to terminate?" i dont want to terminate the container, i want to terminate the specific process (not main process) (sty for misunderstanding , my bad) here is my full code 
at first i create and run the ubuntu container
```
CreateContainerResponse ubuntu_container
                = dockerClient.createContainerCmd("ubuntu:16.04")
                .withCmd("/bin/bash", "-c", "while true; do sleep 1000; done")
                .withName("ubuntu")
                .exec();
        dockerClient.startContainerCmd(ubuntu_container.getId()).exec();

```
after that user click on container on webapp ui and open the virtual terminal and execute some command (like ping), here i create and execute ping command in the container.
```
ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(ubuntu_container.getId())
                .withAttachStdout(true)
                .withCmd("ping", "google.com")
                .withUser("root")
                .exec();

        dockerClient.execStartCmd(execCreateCmdResponse.getId())
                .exec(new ExecStartResultCallback(System.out, System.err));

```
after that user press ctrl-c and the ping command(that is now running) must be terminated( just the ping command not container main process). hop you get it... :)

**Comment by bhowell2** [comment]
I believe I understand now. 

I haven't tried using docker-java for `exec` before and I'd have to mess with it.

I'm not 100% sure how you/docker-java is connecting to this secondary process, but I would think `ctrl-c` would exit that as you're expecting (it works fine when using `docker exec -it /bin/bash` from the local terminal after all -- it's like you're connecting to the main process instead of the secondary-executed one.) I don't have time to look into this right now, but might be able to get back to it later.

You may also want to check out the API for some extra help/tips: https://docs.docker.com/engine/api/v1.37/#operation/ContainerExec 

Two more suggestions: 
1. (Easier) Create a generic SSH container and pipe back and forth between (there are java libraries to talk to SSH servers) it from your server and user (see: https://docs.docker.com/engine/examples/running_ssh_service/#run-a-test_sshd-container) Or you can make that SSH container public and use a javascript emulator like: https://github.com/billchurch/WebSSH2  
2. (Harder/more time consuming)Write an embedded server that can talk to your main webserver that will deal with talking to the container's terminal (there are plenty of java programs that will talk to a terminal for you too).

**Comment by xbj110825** [comment]
I found a way to terminate specific process by sending 0x03(control character: end-of-text ^C) to it's stdin.
```java
DockerClient dockerClient = dockerClient();
String exeId = dockerClient.execCreateCmd("1d87fe71c8bb")
        .withCmd("ping", "127.0.0.1")
        .withAttachStdin(true)
        .withAttachStdout(true)
        .withAttachStderr(true)
        .withTty(true)
        .exec().getId();

PipedInputStream pipedInputStream = new PipedInputStream();
PipedOutputStream pipedOutputStream = new PipedOutputStream();
pipedInputStream.connect(pipedOutputStream);

ResultCallback.Adapter<Frame> execCallback = dockerClient.execStartCmd(exeId).withStdIn(pipedInputStream)
        .exec(new ResultCallback.Adapter<Frame>() {
            @Override
            public void onNext(Frame object) {
                try {
                    System.out.write(object.getPayload());
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            }
        });
Thread.sleep(3000);
pipedOutputStream.write(3);
execCallback.awaitCompletion();
```
Ping process exits in three second.
```text
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.045 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.054 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.045 ms
^C
--- 127.0.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2010ms
```
