### ISSUE TITLE
how to specify --net when create a container

### ISSUE THREAD

**Issue by howaric** [docker-java/docker-java#1076]
hi, I don't find --net configuration when I try to create a container with dockerClient.createContainerCmd().with?, there seems no some withNetwork for users to set a network name, doesn't it support now? or will it be supported later. Thank you.

**Comment by nkedel** [comment]
I'm facing the same issue.  My guess is that it's supported, but just not with an obvious naming?

**Comment by EHJ-52n** [comment]
You can use [CreateContainerCmd.withNetworkMode(String networkMode)](https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java#L251) and provide the network name as `networkMode`.

The problem is that the method is deprecated and I am not sure which alternative should be used in the future. See https://github.com/docker-java/docker-java/issues/1281#issuecomment-601326488.

**Comment by EHJ-52n** [comment]
Following https://github.com/docker-java/docker-java/issues/1281#issuecomment-601331581 you better use:

 `CreateContainerCmd.withHostConfig(HostConfig.newHostConfig().withNetworkMode(String networkMode)`
