### ISSUE TITLE
How to read the IP addresses of swarm tasks?

### ISSUE THREAD

**Issue by kamalhakim** [docker-java/docker-java#1140]
Hi,

Is there any way to read the ip address of swarm tasks? 

I make a docker client poniting to the leader of the swarm via:

```
   DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder() .withDockerHost("unix:///var/run/docker.sock").build();
   DockerClient client = DockerClientBuilder.getInstance(config).build();
```

I read the tasks of a service by:

```
    List<Task> tasks = client.listTasksCmd().withServiceFilter(serviceName).exec();
```

Then I tried the following two ways to find the ip address of a task:

1) fetching continer by id:

```
   TaskStatus status = task.getStatus();
   TaskStatusContainerStatus containerStatus = status.getContainerStatus();
   String containerID = containerStatus.getContainerID();
   List<String> idfilter = new ArrayList<>();
   idfilter.add(id);
   List<Container> list = client.listContainersCmd().withShowAll(true).withIdFilter(idfilter).exec();
```

2) fetching container from overlay network:

```
   List<Network> netList = client().listNetworksCmd().withNameFilter(new String[]{netName}).exec();
   Network network = netList.get(0);
   Map<String, Network.ContainerNetworkConfig> containers = network.getContainers();
```

But both return an empty list - or they do not return the containers that are placed on other swarm nodes. 

Is this feature supported in the API? 

Thanks!

**Comment by kamalhakim** [comment]
It seems the Java-API doesn't support this. 
In case you want to fetch it through docker engine rest API, you can `inspect` the swarm network that the container is launched in the verbose mode.

**Comment by KostyaSha** [comment]
So inspect network command is missing?

**Comment by guidbona** [comment]
@kamalhakim I'm also trying to get the task IPs using your method 2, but, as per [https://docs.docker.com/engine/api/v1.37/#operation/NetworkList](https://docs.docker.com/engine/api/v1.37/#operation/NetworkList) the listNetworks API returns a reduced version of the Network, specifically the containers are not propagated; this can be solved using inspectNetwork.
The problem now is that the Name attribute, documented in the API, is not mapped in the Network.ContainerNetworkConfig structure, and that would allow to link the IP back to the service task, since the container name is a concatenation of the task name and the task ID.
So at the moment the only way is to also inspect the container, which is probably not possible when talking to a Swarm manager and the container is on a different node.

**Comment by kamalhakim** [comment]
@KostyaSha Exact, `network inspect` has to be supported with the info docker rest returns in the `verbose` mode.

@guidbona I ended up launching a socat container in order to enable my java code to send direct rest calls to docker engine. Then I had to parse the returned json to find the list of ips.

**Comment by regbo** [comment]
I created a PR that would solve this with an unrecognized field function:
https://github.com/docker-java/docker-java/pull/1616
