### ISSUE TITLE
Problem with Jersey and other JAXRS providers

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#133]
Hi, currently we are using docker-java in Arquillian Cube so we can write integration tests using Arquillian and Docker. We have several users that have had one problem which is recurrent. they are using RESTEasy as jaxrs provider, and arquillian cube for writing their tests. The problem is that when they run the test there is an exception from docker-client that it doesn't know which provider use and of course the test cannot be executed.

I think that for a generic library like docker-client should avoid using these kind of spi. Keep in mind that the same problem may occurs if user uses another version of jersey. So in fact what is happening here is that a library is fixing the version of the product.

I think that docker-client should not depend on jersey nor any jaxrs implementation and use native HttpUrlConnection to interact with docker server and for example and use an small light none dependent library like json.jar to parse json.

WDYT?

**Comment by marcuslinke** [comment]
Just as it sounds absolutely reasonable to me i think its rather a question of effort. The move from jaxrs client to another http/rest client should be relatively simple but keep in mind all the SSL-/ unix-socket stuff that comes into play here. Saying this i'm not sure it will be that easy anymore.

For me personally docker-java hasn't first priority anymore so i will not investigate into this myself but i'm open for contributions in this direction of course. So what it needs here first is some working sample code that is capable of doing http(s), unix-socket and JSON mapping.

The docker-java api and core classes are already independent of any rest client lib so it needs "only" an alternative ```DockerCmdExecFactory``` implementation.

**Comment by vjuranek** [comment]
:+1:  agree ([similar issue](https://issues.jenkins-ci.org/browse/JENKINS-25692) in Jenkins)

@lordofthejars btw: while agree with this issue, class loader isolation in Arquillian would be also nice to have ;-)

**Comment by marcuslinke** [comment]
This is related somehow: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/docker-java-dev/9WhiNnHtteM/u4KnjZTzib8J

@lordofthejars So it seems docker-java works with CFX mostly without problems. Maybe it is possible to fix these interopability issues with RESTEasy also? What are the exact exceptions when using RESTEasy as jaxrs provider with Arquillian Cube?

**Comment by lordofthejars** [comment]
Well that there are two implementations of same provider, now we are discussing with some Red Hat guys the best way to face this problem. BTW Aslak has just sent you to PR to reduce the size of the library. HE has touched unix socket project and removed guava form docker-java.

**Comment by marcuslinke** [comment]
@lordofthejars Sorry. Now i got it.

**Comment by aslakknutsen** [comment]
Just FYI, I've started some work here; 
https://github.com/aslakknutsen/docker-java/compare/pure_httpc

Not 100% yet, but 99.9% of the test suite run. (not tested SSL stuff yet as I know there is some work there)

Unix and Http work just fine. 

So far removed Jersey and just using Apache HTTP Client directly behind a tiny jax-rs ish api.

**Comment by marcuslinke** [comment]
@aslakknutsen Looks promising! I'm curious if you can get SSL stuff running too. Good luck!

**Comment by gesellix** [comment]
@aslakknutsen without putting too much self-marketing here, I'd like to point you to the sibling project of the unix-socket-factory. It works on the same layer by providing a SocketFactory and more or less transparently uses the Docker certificates. See https://github.com/gesellix/docker-socket-factory for the actual code.

Why I want to mention it here is due to your comment on using the Apache HTTP client and that the linked project also works with the Apache HTTP client. If you like, I can rewrite it from Groovy to a Java - just like you already did with the unix-socket-factory.

As you probably know, with Apache HTTP client 4.3.x some interfaces have been deprecated, which is considered in the [HttpsSocketFactory](https://github.com/gesellix/docker-socket-factory/blob/master/src/main/groovy/de/gesellix/socketfactory/https/HttpsSocketFactory.groovy).

Please see it as inspiration and feel free to copy any code you need.

**Comment by aslakknutsen** [comment]
@gesellix Thanks for the hint. I'll look into it.
