### ISSUE TITLE
Is there a more detailed document

### ISSUE THREAD

**Issue by bqlwx111** [docker-java/docker-java#1428]
I met some problems in the learning process. Is there a more detailed document?Thank you！！！

**Comment by bsideup** [comment]
No, there is no such at the moment. `docker-java` is a low level library. Consider using libraries on top of it (like [Testcontainers](https://www.testcontainers.org)) if you want higher level constructions that are easier to consume.

You can also ask questions in the Gitter channel, so that others can share their experience with you:
https://gitter.im/docker-java/docker-java
