### ISSUE TITLE
Closing chunked stream blocks connection and abandons it from the connection pool forever

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#196]
Using the EventsCmd a connection is blocked when EventsCmdExec is trying to close it. Seems it is a threading issue.

**Comment by jtnord** [comment]
this is not a connection leak but a livelock of the thread.

```
	SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available [native method]	
	SocketInputStream.read(byte[], int, int, int) line: 150	 **<-- this will block until there is another event or the server closes the connection!**
	SocketInputStream.read(byte[], int, int) line: 121	         ** <-- calls above with the default timeout (zero)**
	SessionInputBufferImpl.streamRead(byte[], int, int) line: 136	
	SessionInputBufferImpl.fillBuffer() line: 152	
	SessionInputBufferImpl.readLine(CharArrayBuffer) line: 270	
	ChunkedInputStream.getChunkSize() line: 240	
	ChunkedInputStream.nextChunk() line: 206	
	ChunkedInputStream.read(byte[], int, int) line: 169	
	ChunkedInputStream.read(byte[]) line: 198	
	ChunkedInputStream.close() line: 287	  ** <-- as we are at the end of a complete chunk it helpfully gets the next chunk... and then the next... and the next...!!!!**
	ResponseEntityProxy.streamClosed(InputStream) line: 126	
	EofSensorInputStream.checkClose() line: 227	
	EofSensorInputStream.close() line: 174	
	BufferedInputStream.close() line: 483	
	ApacheConnector$HttpClientResponseInputStream(FilterInputStream).close() line: 181	
	ApacheConnector$HttpClientResponseInputStream.close() line: 643	
	InboundMessageContext$EntityContent(EntityInputStream).close() line: 157	
	InboundMessageContext$EntityContent.close(boolean) line: 151	
	ClientResponse(InboundMessageContext).close() line: 909	
	InboundJaxrsResponse.close() line: 163	
	EventsCmdExec$EventNotifier.call() line: 82	
	EventsCmdExec$EventNotifier.call() line: 46	
	FutureTask<V>.run() line: 266	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1142	
	ThreadPoolExecutor$Worker.run() line: 617	
	Thread.run() line: 745	
```

**Comment by jtnord** [comment]
the javadoc for `ChunkedInputStream.close()` states

> Upon close, this reads the remainder of the chunked message, leaving the underlying socket at a position to start reading the next response without scanning.

Which is useless for us as the chunked response from docker will never cease unless we are forced to use until=<a very short timeout>.

BTW - to reproduce this is simple - just have your `com.github.dockerjava.api.command.EventCallback.onEvent` throw a `RuntimeException`
and don't use a since or until in your event query.

**Comment by jtnord** [comment]
filed [upstream](https://issues.apache.org/jira/browse/HTTPCORE-402)

**Comment by marcuslinke** [comment]
@jtnord That's really a strange implementation of a ```Closable```. Hopefully the apache guys will provide a solution soon. Thanks for investigations.

**Comment by jtnord** [comment]
So upstream say not a bug with a real example of how to close a connection.
So that points at bad handling in Jersey, so a little sniffing around later and I found [JERSEY-2558](https://java.net/jira/browse/JERSEY-2558).  This says that chunked encoding is broken between 2.8 and 2.15.  As docker-java uses 2.11 we have a candidate.

I have update my app to use jersey 2.17 and the issue where I observed the loop is no longer present.

All is not completely peachy though - as I see the connections are not correctly closed.
A network capture shows that is the the docker server that is acking the FIN from the client, but is not itself sending a FIN - so the issue seems to be with docker here.

Given that I would recommend an update to jersey 2.17

**Comment by marcuslinke** [comment]
@jtnord Unfortunately switching to jersey 2.17 doesn't resolve this issue. Still the same behavior. Closing the ```javax.ws.rs.core.Response``` or the entity ```InputStream``` causes the connection to hang forever. So it might be an issue of the jersey apache connector...

**Comment by marcuslinke** [comment]
Following the apache documentation (http://hc.apache.org/httpcomponents-client-4.4.x/tutorial/html/fundamentals.html#d5e145) it seems it needs access to the ```CloseableHttpResponse``` to close the underlying connection really. Sadly it is not offered by jersey apache connector.

**Comment by marcuslinke** [comment]
https://java.net/jira/browse/JERSEY-2852

**Comment by jtnord** [comment]
@marcuslinke so it works for me as I was stopping the client and executor in onException rather than onCompletion.
onCompletion isn't being called as the [close](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/EventsCmdExec.java#L82) is throwing an exception (but the connection does get cleaned up)

In the interim I would suggest wrapping the [close](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/EventsCmdExec.java#L82) with a try catch so that clients are called - wdyt?  (this would allow users to make some progress whilst waiting for jersey to do the right thing?)

**Comment by marcuslinke** [comment]
@jtnord Sorry, i don't understand. Could you provide a code snippet for your test case/scenario please? Switching to jersey 2.17 has no effect in my local test scenario. Neither an exception is thrown when [```close()```](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/EventsCmdExec.java#L82) is called nor  ```onException``` gets executed, so i can't follow you here. It would be nice if you could post some details regarding your tests. Thanks!

**Comment by marcuslinke** [comment]
Just pushed a workaround. In fact I've just copied all the `ApacheConnector` stuff and fixed it. Closing for now.

**Comment by patelrit** [comment]
How about #189? It is dependent on this fix.

**Comment by marcuslinke** [comment]
@patelrit Will wait for feedback first. If all is fine now i will merge your PR.

**Comment by marcuslinke** [comment]
For the files: PR for jersey: https://github.com/jersey/jersey/pull/164

**Comment by marcuslinke** [comment]
@alexec Seems `FrameReaderITest`is not working anymore. Could you take a look please?

**Comment by alexec** [comment]
@marcuslinke  - I think it's due to trying to pull an image. Can you see if there's a related task?

**Comment by marcuslinke** [comment]
After a few changes i have the test running again locally. But i don't understand why the fixed `ApacheConnector` stuff affects the behavior of `FrameReaderITest`. Seems to be something timing related. I will push my changes soon so you can review it.

**Comment by marcuslinke** [comment]
@alexec See https://github.com/docker-java/docker-java/commit/2df09cdca8bd41cb5be0b28e00fbd72632d4f33c

Unfortunately I've reformatted the sources. Hope you can track my changes nevertheless. In summary i did the following:

1. Adopted Dockerfile for the test container so is not running infinitely anymore
2. Wait for successful build of the image
3. Start and wait for successful execution of the container before test the log stream processing of `FrameReader`
4. Don't use 'followStream' option with logging command as it would block reading of the `InputStream`.

**Comment by marcuslinke** [comment]
@alexec Are you satisfied with my changes to `FrameReaderITest`.

**Comment by alexec** [comment]
Yes.  I guess the next step,would be for me to try and find a way to figure out when no more data is available and close the stream?

**Comment by marcuslinke** [comment]
The problem here is with unbound streaming thus using log command  'followStream' option or using events command without 'until' option. If the server returns an unbound stream normally there is no chance to cancel the stream as `InputStream#read()` blocks while waiting for chunks to come from the server. This can be solved only by using separate threads as in the events command implementation.

I'm still unsatisfied with these different streaming APIs in docker-java. I think all streaming commands should use the same callback driven API as in events command.

WDYT?
