### ISSUE TITLE
CommitCmd does not use the tag when saving the image

### ISSUE THREAD

**Issue by plandevida** [docker-java/docker-java#1997]
Hi,

I've been using the library for my project and it seems I encounter an issue when I try to commit a container to an image.

Here is highlighted the image of the running the container:
<img width="941" alt="Screenshot 2022-11-10 at 13 25 29" src="https://user-images.githubusercontent.com/1167738/201092895-60c7f6f3-2844-4865-81bc-6af3ad4cb515.png">

This is the container and you can see the image is the same as above:
<img width="1035" alt="Screenshot 2022-11-10 at 13 37 28" src="https://user-images.githubusercontent.com/1167738/201093809-b17c4abd-99b8-4cfb-a689-fc0f88cdb447.png">

And there after the commit command you can appreciate the image does not have tag:
<img width="943" alt="Screenshot 2022-11-10 at 13 27 33" src="https://user-images.githubusercontent.com/1167738/201093098-f960b5e4-70b5-493d-ae84-287cf9bedbed.png">

The code that does the commit looks like this:
`
try (CommitCmd cmd = this.client.commitCmd(instanceId).withContainerId(instanceId).withTag(tag)) {
       String commitedImageId = cmd.exec();
}
`

**Comment by plandevida** [comment]
Hi,

Could anyone tell me if this is an actual bug?

Regards.

**Comment by AleAntunez** [comment]
The problem is that you are not tagging your image on a repo. 
Reviewing the Docker Engine source code I found the following: 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1734346/202923747-da5d1e0d-90b4-4688-9b15-61fa290d4cf2.png">

They commit the container to a 'random' image ID, and after that, and only if you have specified a repo, the image gets tagged to the provided argument. I think the commit command should work independently of the registry... but in this case is Docker API fault for not clarifying that.

Please check that providing a registry solves the issue.

**Comment by eddumelendez** [comment]
Thanks for sharing your findings, @AleAntunez !
