### ISSUE TITLE
push exec closed before

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#310]
Maybe resolved in 2.x, but will keep for now, 
This code from docker-plugin fails to push second image because first didn't end it's command:
https://github.com/jenkinsci/docker-plugin/blob/bf893a8e20c9688b5862c62ebe5f2c5356457732/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderPublisher.java#L262-L282

Hope callbacks will solve and it not a docker api...
Btw, test case can be two built images with different tags that will be pushed one by one in code.

**Comment by marcuslinke** [comment]
What do you mean by it fails? I guess the  `InputStream pushResponse` must be closed after copying to `ByteArrayOutputStream`. Otherwise the underlying connection is not released to the connection pool which may lead to an empty connection pool.

In v2.x the default callback implementation does closing for your when you wait for successful completion via `awaitSuccess`.

**Comment by KostyaSha** [comment]
Copy prints not full output, probably exec didn't wait for the end or stream wasn't full. In general command continue execution on server side.

**Comment by KostyaSha** [comment]
@marcuslinke don't worry, i will verify and close after 2.1 release, just want keep it here just in case somebody else will have the same issues.

**Comment by KostyaSha** [comment]
Probably readTimeout issue or fixed with 2.1.0
