### ISSUE TITLE
Deadlock on "logContainerCmd"

### ISSUE THREAD

**Issue by bsideup** [docker-java/docker-java#339]
Hi! With latest (2.1.1) docker-java I'm getting flaky deadlock (on frame read) when I'm I use `logContainerCmd` with `withFollowStream` option.

**Comment by KostyaSha** [comment]
Any logs, thread dumps?

**Comment by bsideup** [comment]
@KostyaSha yes, sure :)
https://gist.github.com/bsideup/3eba787e900932169b9a

logging is disabled, but I can enable it if it will help somehow

**Comment by bsideup** [comment]
could be an issue with Jersey: https://java.net/jira/browse/JERSEY-2804

**Comment by marcuslinke** [comment]
You could try to increment to connection pool size and see if it helps. Maybe you forgot to consume an `InputStream` somewhere in your app?

Beside this: `withFollowStream` option means following the log stream INFINETLY. It borrows a connection from the connection pool that must be handed back to the pool when it is not needed anymore. This must be done via `close()` on the exec callback. Otherwise multiple executions of a log command will empty the pool. Maybe you forgot to call close() somewhere?

**Comment by marcuslinke** [comment]
@bsideup Any news?

**Comment by bsideup** [comment]
@marcuslinke I now call "close" in stream and looks like it's working. Still a little bit unexpected behaviour, too low level IMO. Also, InputStream contains stream header from Docker which is also could be handled by docker-java (first 8 bytes of reply)

**Comment by marcuslinke** [comment]
>  I now call "close" in stream and looks like it's working. Still a little bit unexpected behaviour, too low level IMO

In general `InputStream`s that are returned from docker-java must be either fully consumed or `close()`d as there is an underlying connection opened. Otherwise the connection pool will exhaust.

As `withFollowStream` option on log container command means following the log stream INFINETLY you have to tell when you want to abort via `close()` on exec callback. docker-java can't handle this for you.

> Also, InputStream contains stream header from Docker which is also could be handled by docker-java (first 8 bytes of reply)

What do you mean? Log container command API is callback-based and provides `Frame`s.

**Comment by bsideup** [comment]
@marcuslinke BTW just checked - if there are multiple "withFollowStream" loggers then I see deadlocks as well

**Comment by bsideup** [comment]
@marcuslinke where can I configure connection pool?

**Comment by marcuslinke** [comment]
Take a look here:  https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced

**Comment by bsideup** [comment]
@marcuslinke ok, thanks. One more question - is Docker client thread safe? Should I use 1 client instance everywhere, or should I create many of them?

**Comment by marcuslinke** [comment]
As docker client is not tested for thread safety I would suggest to use multiple client instances.
