### ISSUE TITLE
Make DockerException checked exception?

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#366]
When i'm using container stop/start/pull cmds i should handle errors like NotFoundException to define what to do. DockerException is unhandled RuntimeException :atm: 
Proposal: change it to handled.

Comparison to docker-client
https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DockerException.java#L20

**Comment by marcuslinke** [comment]
I don't like checked exceptions. I hate them... There are methods that could throw multiple different exceptions that must all be handled explicitely by client code whether they are of any use or not in the client context. Consider `UnautorizedException` or `InternalServerErrorException` for example. What should you care about it in the client code when you are sure that it normally can't occur? You couldn't do anything useful to handle this situations rather than printing some failure message.

**Comment by KostyaSha** [comment]
Error will end code in the same way, but error can be catched/re-throwed in obvious way in higher logic. It can indicate that this method may throw docker exception or not. Auth error is something that high level and wouldn't allow any operations, docker containers is lower, run/pull errors is very expected errors. 
I.e. if container not found during stop, then i shouldn't try remove it, but if other error occured i should force rm it. 

My current logic catches `Exception` seems it more stronger on container actions.

**Comment by marcuslinke** [comment]
All this can be done without making the exceptions checked. And as I said. I don't like to catch exceptions that I can't do anything to recover from. 

From https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html

> If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.

Someone can't recover from a `NotFoundException` as he obviously doesn't have the right container id.

**Comment by KostyaSha** [comment]
Then container can be started or some other action can be done :)

**Comment by marcuslinke** [comment]
Yes, but that would be business logic and not error handling.

**Comment by marcuslinke** [comment]
Maybe NotFound should not be modeled as an exception?

**Comment by KostyaSha** [comment]
But hande-able errors is business logic. And because of hidden exceptions i surprisingly lost logic...

**Comment by KostyaSha** [comment]
Btw as i see you just followed `javax.ws.rs.NotFoundException` implementation.

**Comment by marcuslinke** [comment]
Right. And in my opinion business logic should not rely on catching exceptions ideally. Exceptions are for signaling error conditions only. They should be avoided from the business logic. I think the problem is the lack of an explicit method to check whether a container exist. 

Once more again: Why should the user be bothered with a checked `NotFoundException` if this exception could not occur normally?

pseudo-code:
```
containerId = createContainer
try {
startContainer(containerId)
} catch(NotFoundException nf) {
   // what should I do here?
} catch(InternalServerErrorException ue) {
} ...
```

**Comment by KostyaSha** [comment]
```
containerId = createContainer
boolean exists = false;
try {
startContainer(containerId);
exists = true;
} catch(NotFoundException nf) {
} catch(InternalServerErrorException ue) {
} ...

if (exists) {
 removeContainer()
}
```
Though it not very valid for other possible exceptions...

**Comment by KostyaSha** [comment]
> Once more again: Why should the user be bothered with a checked NotFoundException if this exception could not occur normally?

Well in jenkins plugins exception usually a valid implementation case that should raise to user messages. Exact exception may help provide better guide to end user, though in jenkins it usually good to catch Exception.

My expectation that `exec` should have some valid exceptions, i.e. i'm using docker controls layer and it can raise errors for some commands (analogue linux processes that has exit codes for defining flow). As soon as i get unexpected exception that stopped logic i'm starting catching the whole `Exception`. 

PS I have no strict opinion about checked vs unchecked.

**Comment by marcuslinke** [comment]
Why did you introduce `exists` flag? If you just created the container you can be sure it exists. In this concrete use-case it makes no sense to catch the exception as you can't do anything to recover.

**Comment by KostyaSha** [comment]
@marcuslinke the truth is that you can't be sure as some parallel logic may decide wipe it.
The other case when you `started` it and then wants `stop` it, but start may fail in any time as it depends on what was run in container.

**Comment by KostyaSha** [comment]
Seems related https://github.com/docker-java/docker-java/issues/353

**Comment by cowwoc** [comment]
I've summarized my viewpoint here: https://stackoverflow.com/a/19061110/14731

In the case of this particular API, regardless of whether you proceed with checked or unchecked exceptions, you should absolutely document all expected exceptions.

> And in my opinion business logic should not rely on catching exceptions ideally. Exceptions are for signaling error conditions only. They should be avoided from the business logic. I think the problem is the lack of an explicit method to check whether a container exist.

I disagree. The method can always throw an exception because race-conditions allow a container to get deleted between the time you check whether it exists and the time you try interacting with it.

Also, see this counter-example:

````
    /**
     * Stops and removes a container, ignoring any errors that occur along the
     * way.
     *
     * @param containerId the id of the container
     */
    private void stopAndRemoveContainer(String containerId) {
        try {
            docker.stopContainerCmd(containerId).exec();
        } catch (NotFoundException | NotModifiedException ignore) {
            // Acceptable failure
        }
        try {
            docker.removeContainerCmd(containerId).exec();
        } catch (NotFoundException ignore) {
            // Acceptable failure
        }
    }
```

Anyway, I'm going to circle back and point to https://stackoverflow.com/a/19061110/14731
