### ISSUE TITLE
swarm support

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#395]
@marcuslinke let's catch here how it supposed to be supported.

Does swarm return any own versions? What docker response version it return then?

**Comment by marcuslinke** [comment]
Seems swarm-manager has its own versioning and supports a specific docker remote API version. This is from an old swarm installation when calling the `/version`endpoint:

```
{
    "ApiVersion": "1.16",
    "Arch": "amd64",
    "GitCommit": "28cd51b",
    "GoVersion": "go1.3.3",
    "KernelVersion": "",
    "Os": "linux",
    "Version": "swarm/0.3.0"
}
```

**Comment by KostyaSha** [comment]
need compare with direct docker. 
My main concern is about using existed classes vs some additional swarm methods or indicators like `client.isSwarm()`
Does swarm support multiple versioned api endpoints? If yes then it may conflict in possibility specify different versioned api (swarm?/docker?)  endpoints.

**Comment by marcuslinke** [comment]
I guess swarm supports multiple versioned API backends as long as they are compatible with the swarm API version. The docker engine should theoretically support multiple API versions via the `/v.../` URL prefix and I think this is what swarm-manager will use when talking to its backends.

**Comment by xFragger** [comment]
https://docs.docker.com/swarm/api/swarm-api/ 
I'm using the client with swarm already, a few features are missing, but it works mainly, the docs say "The Docker Swarm API is mostly compatible with the Docker Remote API. This document is an overview of the differences between the Swarm API and the Docker Remote API."

**Comment by KostyaSha** [comment]
@xFragger we know about this page, but swarm itself may have changes in API and docker behind it also.

**Comment by marcuslinke** [comment]
Current state taken from https://github.com/docker-java/docker-java/pull/443
> What we need for swarm related changes is an integration test case. See #337 please for a proposal. I've currently no time for implementing a setup as described there. Feel free to provide an PR with an integration test setup and we can start to merge swarm related things into master

**Comment by KostyaSha** [comment]
@marcuslinke atm i'm reviewing pull/pushes and auth to get full container lifecycle support in jenkins. As next step i plan start reworking tests and then it will be possible to introduce swarm (because i will also do integration tests for swarn in jenkins plugin).

**Comment by xFragger** [comment]
@KostyaSha i just wanted to build a suite for swarm integration tests today, wondering if its possible to run master and agent on one node and drive tests against it. 
But if you do so anyway, i don't have to... right?

**Comment by KostyaSha** [comment]
@xFragger you can do if you wish.

**Comment by xFragger** [comment]
i will try... lets see what is possible today... 
any suggestions?
my idea was to just use the AbstractDockerClientTest as a base for a new AbstractDockerSwarmClientTest

**Comment by md-5** [comment]
I see that PR, I'll happily chuck in $50USD when it's pulled to get the container.inspect Node data exposed, that's all I care about for "swarm support".

**Comment by xFragger** [comment]
Just leave me some information, what is missing. I've got 6-8hours every second friday for that, in theory, for helping out with that.

**Comment by md-5** [comment]
Nothing is missing that I can see, just want to get it merged :D

**Comment by garagatyi** [comment]
I'll try to help by sharing my experiens of swarm managing over API.
You should be aware that Swarm uses Docker API client for v1.15. Prove [here](https://github.com/docker/swarm/blob/master/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go#L20). I create an [issue](https://github.com/docker/swarm/issues/1912) to upgrade it, but haven't got any response from the community.
Swarm add node entry to Container info that has such fields:
`id, name, addr, ip, cpus, memory, labels`
Swarm performs pull on ALL nodes. There is no API to do that on one node or specific node. But there is workarounds with labels or manual pulling with bypassing Swarm and communicating to Docker directly.
There was problems with authentication, but looks like they fixed some of these problems (I haven't checked).
I would reccomend to add new exception for swarm. When it can't deploy container due to lack of resources it returns 500 error with message "no resources available to schedule container". So OutOfResourcesException would be helpful.
To get information about available nodes you have to parse output of /info endpoint. And it changes so often! Honestly it is not well structured JSON because it is array with not defined order of entries. So they changed order several times! I had a lot of troubles because of that.

**Comment by KostyaSha** [comment]
fighting with integration tests #711 
then #337 and `Node` field ...
Exception if it exists would be also needed but i hope it would be possible to make some tests.

**Comment by KostyaSha** [comment]
@marcuslinke i will forward master to 3.1.0 before merging swarm stuff, swarm-mode is also prepared in other PR.

**Comment by Fabryprog** [comment]
Hello everyone. What is the current state of feature?

**Comment by enen92** [comment]
^^ also interested. I guess (https://github.com/docker-java/docker-java/pull/717) is showing the current state?

**Comment by bsideup** [comment]
Swarm is supported now.

**Comment by vishalpaalakurthi** [comment]
> Swarm is supported now.

Can you please provide information about configuring docker swarm client.

> 
>  dockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder()
>                 .withDockerHost(SystemUtils.IS_OS_WINDOWS ? "tcp://localhost:2375" : "unix:///var/run/docker.sock")
>                 .build();

Above one is not working
