### ISSUE TITLE
On back porting CopyArchive*Container commands

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#485]
Any chance we can get these 2 classes back ported to the 2.2.x line before you guys move to 3.0?

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/CopyArchiveToContainerCmdImpl.java

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/CopyArchiveFromContainerCmdImpl.java

**Comment by marcuslinke** [comment]
2.x line is only bugfixed now. You could switch to "3.0.0-RC1". Or is there anything that prevents you from doing so?

**Comment by cdancy** [comment]
@marcuslinke from what I've read, and correct me if I'm wrong, is that the 3.0 line will be substantially different in the way that commands are invoked and processed? You guys currently support "docker copy file from container" but not it's sister command: "docker copy file to container". Before the change happens, and I have to re-write how the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) works, I was hoping to be able to create a gradle task for copying files to a container using the 2.x line. It's been asked for on our end but we are dependent on you guys as we are essentially a gradle wrapper around this library.

**Comment by marcuslinke** [comment]
@cdancy The 3.0.0-RC1 version is not changing the way commands are invoked.

We have renamed some methods and using objects instead of primitives now in the API (null checks may required now).

Additionally most configuration keys has changed to match better with its shell environment equivalents. Porting existing client code from 2.x to 3.x shouldn't be that big deal. 

You should give it a try. As I stated before the 2.x line will only be bugfixed.

**Comment by cdancy** [comment]
@marcuslinke fair enough and we will have to do so anyway eventually ;)

**Comment by marcuslinke** [comment]
OK. So closing this now.
