### ISSUE TITLE
Change Volumes to Mounts for CreateContainerCmd

### ISSUE THREAD

**Issue by mkaluzny** [docker-java/docker-java#523]
It seems that since 1.20 the Volume attribute is gone for create container command, but there is new Mounts attribute for specifying volume mounts. It is now impossible to create a container with mounted volumes.

**Comment by marcuslinke** [comment]
@mkaluzny Could you provide some sample code that is not working for you anymore please?

**Comment by marcuslinke** [comment]
OK, I see. Create container command now has `Mounts` instead of `Volumes`. That seems to be introduced with https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#create-a-container. `Volumes ` are working with 1.22 also probably for backward compatibility reasons. We should provide `Mounts` also in our API.

**Comment by bsideup** [comment]
See `HostConfig#mounts`
