### ISSUE TITLE
readTimeout connectTimeout for netty?

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#588]
@marcuslinke  did i miss something?

**Comment by marcuslinke** [comment]
There are no generic timeouts implemented yet for netty factory. Is it a problem?

**Comment by KostyaSha** [comment]
no, continue comparing. It strange that timeouts are not configurable.

**Comment by marcuslinke** [comment]
Timeouts can be implemented explicitely by insering a special timeout handler into the channel pipeline.

**Comment by KostyaSha** [comment]
@marcuslinke how get SSLContext from already created connection or factory?
Use case, building connection with defaults that reading env vars and then want get created sslconfig/context from execfactory.

**Comment by KostyaSha** [comment]
Hm... and DockerClientBuilder is not usable if i'm not using dockerCertPath because `.build()` calls `DockerClientConfig` constructor that checks `checkDockerCertPath`

**Comment by marcuslinke** [comment]
Maybe we have to introduce `DockerCmdExecFactory.getSSLContext()` then?

**Comment by KostyaSha** [comment]
> Maybe we have to introduce DockerCmdExecFactory.getSSLContext() then?

#591 but i think my main issue is DockerClientConfigBuilder that wants dockerCertPath and doesn't know that SSL could be set in DockerCmdExec because it 2 different classes.

**Comment by KostyaSha** [comment]
And, without readtimeout/connecttimeout client may cause infinite delay, or it bug somewhere. In any case it would make also sense to add them in test clients.

**Comment by pjdarton** [comment]
Hi folks,
I just found this issue while searching for support for setting a readTimeout when using Netty.  The [changelog](https://github.com/docker-java/docker-java/blob/3.0.14/CHANGELOG.md) suggests that this functionality was lost when v2.0.0 arrived (it was implemented for JerseyDockerCmdExecFactory but not for NettyDockerCmdExecFactory).

I think that this missing functionality might be fairly trivial to implement if we can "just" add a few lines to JerseyDockerCmdExecFactory...
If my understanding of the Netty docs for [ReadTimeoutHandler](https://netty.io/4.0/api/io/netty/handler/timeout/ReadTimeoutHandler.html) is correct, all we need to do is to add a new field to NettyDockerCmdExecFactory
```
    private Integer readTimeout = null;
```
add a new method
```
    /**
     * Configure read timeout in milliseconds
     */
    public NettyDockerCmdExecFactory withReadTimeout(Integer readTimeout) {
        this.readTimeout = readTimeout;
        return this;
    }
```
and lastly modify the ```configure``` method so that this new field gets taken into account:
```
    private <T extends Channel> T configure(T channel) {
        ChannelConfig channelConfig = channel.config();

        if (connectTimeout != null) {
            channelConfig.setConnectTimeoutMillis(connectTimeout);
        }
        if (readTimeout != null) {
            channel.pipeline().addLast("readTimeoutHandler", new ReadTimeoutHandler(readTimeout, TimeUnit.MILLISECONDS));
        }

        return channel;
    }
```

As @KostyaSha said [over a year ago](https://github.com/docker-java/docker-java/issues/588#issuecomment-232182860), failure to set a timeout may cause an infinite delay - we have found this to be the case, and we get reminders of this annoyingly often.

In our environment (multiple docker hosts, Jenkins and a [docker-plugin](https://github.com/jenkinsci/docker-plugin) for Jenkins), what we've found is that sometimes the Docker daemon fails in a manner than means that it accepts new TCP/IP connections, but it never answers any API requests so, unless you've got some form of timeout, any call to docker-java can hang indefinitely.  In my case, this was happening when Jenkins called the docker-plugin's ```provision``` method to ask for a new container to be created, and when docker-java locked up, most of Jenkins stopped working (which is why I noticed).
i.e. timeouts are important :-)

We don't want to reconfigure the Jenkins docker-plugin to use Jersey (too many library clashes with the core Jenkins code - we want to stay using Netty) but we really need to ensure that Jenkins gives up on a docker daemon if it fails to respond within 1 minute.


...so, what do you think?  Is this likely to work?  If so, what's the quickest way of making it happen?

**Comment by KostyaSha** [comment]
@pjdarton maintaining is happening on the same quality level, i had enough issues. 

I remember about timeouts and collected different production issues, planning to enhance. In limited time scopes now i only review/merge PRs

**Comment by pjdarton** [comment]
I've implemented a method readTimeout on the Netty side of things.

I've tested this manually with a local build of [docker-plugin](https://github.com/jenkinsci/docker-plugin/) while issuing a ```kill -s STOP <dockerPID>``` on my local docker host and it works as expected - Manage Jenkins -> Configure System -> Add cloud -> Test Connection can (if you configure a read timeout) now give up waiting for a response after the configured time (despite that plugin using Netty).

Merging this PR will then allow both docker-plugin and yet-another-docker-plugin (once enhanced to take advantage of this new functionality) to be able to implement both a "Connection Timeout" and a "Read Timeout" regardless of them using Netty or Jersey.
