### ISSUE TITLE
Run Container with 'docker run --net=my_network'

### ISSUE THREAD

**Issue by sourcecase** [docker-java/docker-java#618]
Hi docker-java coders,
I'm running docker-java within testcontainers to spawn Docker containers for unit testing. The Jenkins server which executes the tests is running is a Docker container as well. The Jenkins Container is spawned in a defined Docker network with the option "docker run --network". 

Is there a way to spawn a testcontainer from java in a non default network?

Regards and thanks
Chris

**Comment by KostyaSha** [comment]
Please follow docker api docs https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container if something missing in models/objects then feel free to open feature request. 
Also note that 1.12 docker is not supported yet, so you need point your dockerclient connetion to previous api version (1.23 afair)

**Comment by rnorth** [comment]
Hi @sourcecase. Please file this as an issue on the testcontainers issue
tracker rather than here, as the docker-java team are not responsible for
testcontainers and, I think, have provided what we need.

I think I have what you're looking for in a branch, due for release soon
after a little bit more prep. Please file an issue and I'll try and tell
you what you need to know.
On Tue, 28 Jun 2016 at 16:24 Kanstantsin Shautsou <notifications@github.com>
wrote:

> Please follow docker api docs
> https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container
> if something missing in models/objects then feel free to open feature
> request.
> Also note that 1.12 docker is not supported yet, so you need point your
> dockerclient connetion to previous api version (1.23 afair)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker-java/docker-java/issues/618#issuecomment-229084151>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIET9dgV_Y9CKgwjWb7MI_gGrole1M6ks5qQTy2gaJpZM4JAN6T>
> .
>
-- 
Richard

**Comment by sourcecase** [comment]
Hi Richard and @KostyaSha ,

sorry for adding this issue in the wrong thread. 
@rnorth Thanks for your help related to my use case. I will open an issue in the testcontainers issue tracker.

Best regards
Chris
