### ISSUE TITLE
Exec multiple commands in one call

### ISSUE THREAD

**Issue by pavolloffay** [docker-java/docker-java#646]
Hello,

I have a question whether it is possible to exec multiple commands in one call.

     commands = new String[] {
                "mkdir " + sNewAbsolutePath + " && " +
                "cp " + sOrigAbsolutePath + " " + sNewAbsolutePath
            };

            ExecCreateCmdResponse exec = dockerClient.execCreateCmd(id)
                    .withCmd(commands)
                    .withAttachStdout(true)
                    .withAttachStderr(true)
                    .exec();

            dockerClient.execStartCmd(exec.getId())
                    .exec(new ExecStartResultCallback(System.out, System.err))
                    .awaitCompletion();

this call above fails.

**Comment by KostyaSha** [comment]
Sorry, but this question is not related to docker-java. You need construct and escape correctly commands or shell script that you are executing. Also docker executing LINUX process and there is no any `&&` for them. Also you need read differences between entrypoint and exec. 
Try experiment with "echo XXX" commands instead of silent commands to understand what is happening.

**Comment by pavolloffay** [comment]
This worked :+1: 
            commands = new String[] {"bash", "-c",
                "echo foo && echo bar",
            };

            ExecCreateCmdResponse exec = dockerClient.execCreateCmd(id)
                    .withCmd(commands)
                    .withAttachStdout(true)
                    .withAttachStderr(true)
                    .exec();

            dockerClient.execStartCmd(exec.getId())
                    .exec(new ExecStartResultCallback(System.out, System.err))
                    .awaitCompletion();
