### ISSUE TITLE
Building of the Tar for your Docker Container is very slow

### ISSUE THREAD

**Issue by monksy** [docker-java/docker-java#657]
My directory in which the docker file references is estimated to be about 3GBs including lots of small files and some compressed. 

When I build the docker file with the command line utility it takes about 6 minutes. When I build the image via the docker-java client it takes 26minutes. Approximately 10 minutes of it is archiving in the tar process, and the rest to transfer it to the local docker-toolbox IP address and to build it out. 

If my understanding of the docker cli command is correct: It's building on the docker host as well (in virtualbox) 

What is the difference here and how can I make the client behave more like the CLI?

**Comment by KostyaSha** [comment]
What docker-java version do you use? Do you use .dockerignore?

**Comment by monksy** [comment]
3.0.1.

Docker ignore: no

-Steven

**Comment by monksy** [comment]
Even without the dockerignore, there is a huge difference between the two.

**Comment by monksy** [comment]
This went to 8 minutes after setting the API version to 1.23.

**Comment by KostyaSha** [comment]
Wow, no idea... Docker-java archives everything into TAR and then upload to docker daemon. Of course some performance degradation may exist. But i would suggest create a `@Test` with your files and measure all steps. Or maybe i mistaken because tar is stream based and can pack files on the fly...  I can also suggest compare docker.log for docker-java vs CLI...
