### ISSUE TITLE
How can i get the ContainerId for a running container using Container name !

### ISSUE THREAD

**Issue by RajAsapu** [docker-java/docker-java#831]
I am looking for method/way to perform the opertion like the below one

> `    public String getContainerIdUsingName(String containerName)
>     {
>         try{
>             Process p = Runtime.getRuntime().exec("docker ps -aqf \"name="+containerName+"\"");
>             BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
>             return stdInput.readLine();
>         }catch (Exception exp){
>             exp.printStackTrace();
>         }
>         return null;
>     }`

**Comment by orzeh** [comment]
@RajAsapu you can use `InspectContainer` command. Please see [InspectContainerCmdImplTest](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/InspectContainerCmdImplTest.java#L62) for example usage. Remember to pass the container name instead of id - they both can be used here as described in the [docs](https://docs.docker.com/engine/api/v1.27/#operation/ContainerInspect).
